### ISSUE TITLE
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation

### ISSUE THREAD

**Issue by taidbui** [DarkMatterAI/mrl#14]
Hi,

I am playing with the tutorials (e.g., tutorials.small_molecule.affinity_active.ipynb) and encountered the error as in the attached screenshot. I'm wondering if it is a bug or there is something with my installation. I installed the latest stable version as well as the dev one, both gave the same error. I used a conda env with Miniforge for apple silicon and python 3.9. 

<img width="985" alt="image" src="https://user-images.githubusercontent.com/28985154/210315359-d0e2673c-5ca4-49ae-a5c4-8d4fa41055d8.png">

Thank you,

TB

**Comment by taidbui** [comment]
Updated: Tested on Colab and similar errors occurred.

**Comment by kheyer** [comment]
Hey there,
What version are you using? This bug was introduced in a previous version, but was fixed in the 1.3 release. I realize I forgot to bump the internal package number, so `mrl.__version__` returns 1.2 for both version 1.2 and 1.3, but your pip/conda install should show the correct version number.

I just ran the small [molecule affinity colab notebook](https://colab.research.google.com/github/DarkMatterAI/mrl/blob/master/nbs/tutorials/tutorials.small_molecule.affinity.ipynb) as is with version 1.3 installed and it worked for me.

**Comment by taidbui** [comment]
Hi, 
It's weird. I have the version 1.3 installed and still have the same problem. I have PyTorch 1.12.1 + python 3.9

**Comment by kheyer** [comment]
Figured it out. The batch state loss is initialized as a leaf variable. When using a GPU, moving the variable to the GPU removes the leaf flag so everything works fine on the GPU, but this error pops up on CPU. I'll try patch this in the next few days. For now a quick fix is to update the `BatchState` class at line 474 of `callback.py` to the code below

```python
class BatchState(SettrDict):
    def __init__(self):
        super().__init__()
        
        self.samples = []
        self.sources = []
        self.rewards = to_device(torch.tensor(0.))
        self.loss = torch.tensor(0., requires_grad=True)
        self.loss = to_device(self.loss.clone())
        self.latent_data = {}
```
